import React from "react";
import Disqus from "disqus-react";
import { NextPage } from "next";
import Head from "next/head";

import Layout from "../public/components/layout";
import Header from "../public/components/header";
import Footer from "../public/components/footer";

const DisqusBlock = () => {
    const disqusShortname = "asianblackalliances";
    const disqusConfig = {
        url: "https://www.asianblackalliances.com",
        identifier: "asianblackalliances",
        title: "Asian Black Alliances",
    };

    return (
        <div>
            <Disqus.DiscussionEmbed
                shortname={disqusShortname}
                config={disqusConfig}
            />
        </div>
    );
}

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>ABA: Discussion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Layout title='ABA: Discussion' description=' '>
                <div id='body'>

                    <h1>Discussion</h1>
                    <DisqusBlock />
                </div>
            </Layout>

            <Footer />
        </>
    )
}

export default Home
