import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import { createClient } from 'next-sanity'

import { Button, Paper } from '@mui/material';

import { useForm, ValidationError } from '@formspree/react';

import Layout from "../public/components/layout";
import Header from "../public/components/header";
import Footer from "../public/components/footer.js";

const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});

const Discussion = ({footerContent, discussionPost}) => {
    return (
        <>
            <Head>
                <title>ABA: Discussion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://use.typekit.net/hco7ora.css" />

            </Head>
            <Header />
            <Layout title='ABA: Discussion' description=' '>
                <div id='body'>

                    <h1>Discussion</h1>
                    <p style={{ textAlign: "center" }}>If you would like to share your own story, plese submit a comment below</p>
                    

            <form action="https://formspree.io/f/xgedrjkp" method="POST">
                <div id="formWrap">
                    <div className="fieldWrap">
                        <input style={{marginRight: "2%"}} type="text" id="name" placeholder="Name" required name="submissionName" />
                        <input style={{marginLeft: "2%"}} type="email" id="email" placeholder="Email" name="email" required />
                    </div>
                    <div className="fieldWrap">
                        <textarea id="message" rows="7" placeholder="Message" name="message" required />
                    </div>
                    <Button variant="contained" type="submit">Send</Button>
                </div>
                    </form>
                    

                    {/* Display each discussion post in a Card below */}
                    {discussionPost.map((post) => (
                        <Paper className="discussionCard">
                            <h2>{post?.title}</h2>
                            <h3>From: {" " + post?.name}</h3>
                            <p>{post?.body}</p>
                        </Paper>
                    ))}

                </div>
            </Layout>

            <Footer 
            link={
          footerContent[0]?.link
        } body={
          footerContent[0]?.body
        } />
        </>
    )
}


export async function getStaticProps() {
    const footerContent = await client.fetch(`*[_type == "footerContent"]  | order(order asc)`)
    const discussionPost = await client.fetch(`*[_type == "discussionPost"]  | order(order asc)`)
    return {
        props: {
            footerContent,
            discussionPost,
        },
    };
}

export default Discussion
