import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import { createClient } from 'next-sanity'


import Layout from "../public/components/layout";
import Header from "../public/components/header";
import Footer from "../public/components/footer.js";

const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});

const Discussion = ({footerContent}) => {
    const [status, setStatus] = React.useState("Submit");
    const handleSubmit = async (e) => {
        e.preventDefault();
        setStatus("Sending...");
        const { name, email, message } = e.target.elements;
        let details = {
            name: name.value,
            email: email.value,
            message: message.value,
        };
        let response = await fetch("http://localhost:5000/contact", {
            method: "POST",
            headers: {
                "Content-Type": "application/json;charset=utf-8",
            },
            body: JSON.stringify(details),
        });
        setStatus("Submit");
        let result = await response.json();
        alert(result.status);
    };

    return (
        <>
            <Head>
                <title>ABA: Discussion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://use.typekit.net/hco7ora.css" />

            </Head>
            <Header />
            <Layout title='ABA: Discussion' description=' '>
                <div id='body'>

                    <h1>Discussion</h1>
                    <p style={{ textAlign: "center" }}>If you would like to share your own story, plese submit a comment below</p>
                    

            <form onSubmit={handleSubmit}>
            <div id="formWrap">
            <div id="nameWrap">
                <input type="text" id="name" placeholder="Name" required />
            </div>
            <div id="emailWrap">
                <input type="email" id="email" placeholder="Email" required />
            </div>
            <div id="messageWrap">
                <textarea id="message" placeholder="Message" required />
            </div>
            <button type="submit">{status}</button>
            </div>
            </form>
                </div>
            </Layout>

            <Footer 
            link={
          footerContent[0]?.link
        } body={
          footerContent[0]?.body
        } />
        </>
    )
}


export async function getStaticProps() {
    const footerContent = await client.fetch(`*[_type == "footerContent"]  | order(order asc)`)
    return {
        props: {
            footerContent,
        },
    };
}

export default Discussion
