import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { createClient } from 'next-sanity'

import styles from '../styles/Home.module.css'
import Header from '../public/components/header'
import Footer from '../public/components/footer'
import Layout from '../public/components/layout'

import Grid from '@mui/material/Grid';

import {
  ComposableMap,
  Geographies,
  Geography,
  ZoomableGroup,
  Marker
} from 'react-simple-maps';

import {
  Timeline,
  TimelineItem,
  TimelineDot,
  TimelineSeparator,
  TimelineConnector,
  TimelineContent,
  TimelineOppositeContent
} from '@mui/lab';

import { Paper, Typography } from '@mui/material';


const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});

const geoUrl = '/features.json';

const HistoryOfCollaboration: NextPage = ({ timelinePoint }: any) => {
  return (
    <>
      <Head>
        <title>ABA: History of Collaboration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout title={'History of Collaboration'} description={' '}>
        <Header />
        <div id='body'>
          <ComposableMap projection="geoMercator" width={800} height={400}>
            <ZoomableGroup center={[0, 0]} zoom={1}>
              <Geographies geography={geoUrl}>
                {({ geographies }) =>
                  geographies.map((geo) => (
                    <Geography key={geo.rsmKey} geography={geo} />
                  ))
                }
              </Geographies>
              <Marker coordinates={[0, 0]}>
                <circle r={3} fill="#FF5533" />
              </Marker>
            </ZoomableGroup>
          </ComposableMap>
          <h1>History of Collaboration</h1>


          <Timeline position="alternate">
            {timelinePoint.map((timelinePoint: any) => (
              <TimelineItem key={timelinePoint._id} sx={{ margin: '2%' }}>
                <TimelineOppositeContent color="text.secondary">
                  {timelinePoint?.date}
                </TimelineOppositeContent>
                <TimelineSeparator>
                  <TimelineDot />
                  <TimelineConnector />
                </TimelineSeparator>
                <TimelineContent>
                  <Typography variant="h6" component="span">
                    {timelinePoint?.title}
                  </Typography>
                  <Typography>
                    {timelinePoint?.body}
                  </Typography>
                </TimelineContent>
              </TimelineItem>
            ))}
            <TimelineItem sx={{ margin: '2%' }}>
              <TimelineOppositeContent color="text.secondary">
                1900s
              </TimelineOppositeContent>
              <TimelineSeparator>
                <TimelineDot />
                <TimelineConnector />
              </TimelineSeparator>
              <TimelineContent>
                <Typography variant="h6" component="span">
                  Two
                </Typography>
                <Typography>                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </Typography>
              </TimelineContent>
            </TimelineItem>
            <TimelineItem sx={{ margin: '2%' }}>
              <TimelineOppositeContent color="text.secondary">
                1950s
              </TimelineOppositeContent>
              <TimelineSeparator>
                <TimelineDot />
                <TimelineConnector />
              </TimelineSeparator>
              <TimelineContent>
                <Typography variant="h6" component="span">
                  Three
                </Typography>
                <Typography>                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </Typography>
              </TimelineContent>
            </TimelineItem>
            <TimelineItem sx={{ margin: '2%' }}>
              <TimelineOppositeContent color="text.secondary">
                1970s
              </TimelineOppositeContent>
              <TimelineSeparator>
                <TimelineDot />
                <TimelineConnector />
              </TimelineSeparator>
              <TimelineContent>
                <Typography variant="h6" component="span">
                  Four
                </Typography>
                <Typography>                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </Typography>
              </TimelineContent>
            </TimelineItem>
            <TimelineItem sx={{ margin: '2%' }}>
              <TimelineOppositeContent color="text.secondary">
                1980s
              </TimelineOppositeContent>
              <TimelineSeparator>
                <TimelineDot />
                <TimelineConnector />
              </TimelineSeparator>
              <TimelineContent>
                <Typography variant="h6" component="span">
                  Five
                </Typography>
                <Typography>                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </Typography>
              </TimelineContent>
            </TimelineItem>
          </Timeline>
        </div>

      </Layout>

      <Footer />
    </>
  )
}

export async function getStaticProps() {
  const timelinePoint = await client.fetch(`*[_type == "timelinePoint"] | order(order asc)`)

  return {
    props: {
      timelinePoint
    }
  };
}

export default HistoryOfCollaboration
