// import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { createClient } from 'next-sanity'

import Header from '../public/components/header';
import Footer from '../public/components/footer';
import MythCard from '../public/components/cards/mythCard';

import Layout from '../public/components/layout';


const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});

export default function MythsCuriosity({myth}) {
  return (
    <>
      <Head>
        <title>ABA: Myths and Curiosity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Layout title='ABA: Myths and Curiosity' description=' '>
        <div id='body'>
          <h1> Myths and Curiosity</h1>
          {myth.map((myth) => (
            <MythCard key={myth._id}
              mythTitle={myth?.title}
              mythDesc={myth?.body}
              mythLink={myth?.link}
              mythLinkNote={myth?.linkNote} />
          ))}
        </div>
      </Layout>
      <Footer />
    </>
  )
}


export async function getStaticProps() {
  const myth = await client.fetch(`*[_type == "myth"] | order(order asc)`);

  return {
    props: {
      myth
    }
  };
}