// import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { createClient } from 'next-sanity'

import styles from '../styles/Home.module.css'
import Header from '../public/components/header';
import Footer from '../public/components/footer';
import MythCard from '../public/components/mythCard';

import Layout from '../public/components/layout';

import Grid from '@mui/material/Grid';

const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});

export default function MythsCuriosity({myth}) {
  return (
    <>
      <Head>
        <title>ABA: Myths and Curiosity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Layout title='ABA: Myths and Curiosity' description=' '>
        <div id='body'>
          <h1> Myths and Curiosity</h1>
          {myth.map((myth) => (
            <MythCard key={myth._id} mythTitle={myth?.title} mythDesc={myth?.body} 
            mythLink='https://www.npr.org/2015/10/15/448840691/how-asian-americans-have-redefined-what-it-means-to-be-american'
            mythLinkTitle='NPR – How Asian-Americans Have Redefined What It Means To Be American'/>
          ))}

          <MythCard
            mythTitle='Myth Title'
            mythDesc='Myth Description'
            mythLink='https://www.npr.org/2015/10/15/448840691/how-asian-americans-have-redefined-what-it-means-to-be-american'
            mythLinkTitle='NPR – How Asian-Americans Have Redefined What It Means To Be American'
          />
          <MythCard
            mythTitle='Myth Title'
            mythDesc='Myth Description'
            mythLink='https://www.npr.org/2015/10/15/448840691/how-asian-americans-have-redefined-what-it-means-to-be-american'
            mythLinkTitle='NPR – How Asian-Americans Have Redefined What It Means To Be American'
          />
          <MythCard
            mythTitle='Myth Title'
            mythDesc='Myth Description'
            mythLink='https://www.npr.org/2015/10/15/448840691/how-asian-americans-have-redefined-what-it-means-to-be-american'
            mythLinkTitle='NPR – How Asian-Americans Have Redefined What It Means To Be American'
          />
        </div>
      </Layout>
      <Footer />
    </>
  )
}


export async function getStaticProps() {
  const myth = await client.fetch(`*[_type == "myth"]`)

  return {
    props: {
      myth
    }
  };
}