import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../public/components/header';
import Footer from '../public/components/footer';

import Grid from '@mui/material/Grid';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ABA: Myths and Curiosity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <h1> Myths and Curiosity</h1>
      </main>

      <Footer />
    </>
  )
}

export default Home
