// import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { createClient } from 'next-sanity'

import { useState } from 'react';

import Header from '../public/components/header';
import Footer from '../public/components/footer.js';
import MythCard from '../public/components/cards/mythCard.js';

import Layout from '../public/components/layout';

import RoadtripMap from '../public/components/roadtripMap';


import { Tooltip } from '../public/components/tooltip';

import { Paper } from '@mui/material'

import dynamic from 'next/dynamic'
const ReactTooltip = dynamic(() => import('react-tooltip'), { ssr: false });
const NewMap = dynamic(() => import('../public/components/newRoadtripMap.js'), { ssr: false });

// import NewMap from '../public/components/newRoadtripMap.js';

const styles = {
  theRadius: {
    borderRadius: '25px',
  },
}

const client = createClient({
  projectId: 'hiagtp2f',
  dataset: 'production',
  apiVersion: '2022-10-03',
  useCdn: false,
});



export default function MythsCuriosity({ myth, footerContent, mythCuriosityHeader, roadtripStop }) {
  const [tooltipContent, setTooltipContent] = useState("");

  const titles = roadtripStop.map((stop) => stop.title);
  const xPositions = roadtripStop.map((stop) => stop.xPos);
  const yPositions = roadtripStop.map((stop) => stop.yPos);
  const body = roadtripStop.map((stop) => stop.body);
  const link = roadtripStop.map((stop) => stop.link);

  
  return (
    <>
      <Head>
        <title>ABA: Myths and Curiosity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/hco7ora.css" />
        <link rel="stylesheet" href="https://use.typekit.net/hco7ora.css" />


      </Head>

      <Header />
      <Layout title='ABA: Myths and Curiosity' description=' '>
        <div id='body'>
          {/* <h1> Myths &#38; Curiosity</h1> */}
          <Paper className='collapsed' sx={styles.theRadius}>
            <a href='#myths' className='collapsed-desc'>
              {/* Display the first item in mythsCuriosityHeader */}
              <h1>{mythCuriosityHeader[1]?.title}</h1>
              <h2>{mythCuriosityHeader[1]?.desc}</h2>
            </a>
          </Paper>
          <div className='collapsed-content' id='myths'>
          {myth.map((myth) => (
            <MythCard key={myth._id}
              mythTitle={myth?.title}
              mythDesc={myth?.body}
              mythLink={myth?.link}
              mythLinkLabel={myth?.linkLabel}
              mythLinkNote={myth?.linkNote} />
          ))}
          </div>

          <Paper className='collapsed'  sx={styles.theRadius}>
            <a href='#curiosity' className='collapsed-desc'>
              <h1>{mythCuriosityHeader[0]?.title}</h1>
              <h2>{mythCuriosityHeader[0]?.desc}</h2>
            </a>
          </Paper>
          <div className='collapsed-content' id='curiosity'>
          {/* <Tooltip tooltipText="Washington, DC"> */}
            {/* <h1>Be Curious on Your Next Roadtrip!</h1> */}
          {/* </Tooltip> */}
            <p style={{ textAlign: "center", maxWidth: '70%' }}>As racial minorities, we do not see our histories taught in formal education. Therefore, we need to self educate with true and comprehensive information. When you plan your next family vacation, consider building in a couple of such lessons to learn about ourselves and each other</p>

          
            {/* <RoadtripMap setTooltipContent={setTooltipContent}/> */}
            {/* <ReactTooltip effect='solid' >{tooltipContent}</ReactTooltip> */}
            <div style={{ height: '500px', width: '90%', margin: "2rem", borderRadius: "25px", overflow: 'hidden'}}>
              <NewMap xPoints={xPositions} yPoints={yPositions} titles={titles} bodies={body} links={link} />
              </div>

            </div>
        </div>


      </Layout>
      <Footer link={
          footerContent[0]?.link
        } body={
          footerContent[0]?.body
        } />
    </>
  )
}


export async function getStaticProps() {
  const myth = await client.fetch(`*[_type == "myth" && language == "en"] | order(order asc)`);
  const footerContent = await client.fetch(`*[_type == "footerContent"]  | order(order asc)`)
  const mythCuriosityHeader = await client.fetch(`*[_type == "mythCuriosityHeader"]  | order(order asc)`)
  const roadtripStop = await client.fetch(`*[_type == "roadtripStop"]  | order(order asc)`)


  return {
    props: {
      myth,
      footerContent,
      mythCuriosityHeader,
      roadtripStop,
    },
    revalidate: 10,

  };
}