import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Header from '../public/components/header'
import Footer from '../public/components/footer'
import Layout from '../public/components/layout'

import React from 'react'


import Grid from '@mui/material/Grid';

import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });



const styles = {
  playerWrap: {
    position: "relative",
    width: "100%",
    paddingBottom: "100%",
  },
  playerStyle: {
    borderRadius: '25px',
    boxShadow: '0px 0px 10px 0px rgba(0,0,0,0.75)',
    border: '1px solid #000000',
    // overflow: 'hidden',
    // maxWidth: '100%',
    position: "absolute",
    maxWidth: "80%",
    maxHeight: "100%",
  },
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ABA: Our Voices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout title='ABA: Our Voices' description=' '>
        <div id='body'>

          <h1>Our Voices</h1>
          <div style={styles.playerWrap as React.CSSProperties}>
            <ReactPlayer url='https://www.youtube.com/watch?v=qjYiuV66KEw'
              width={"auto"} style={{ borderRadius: "25px", overflow: "hidden" }} />
          </div>
        </div>
      </Layout>

      <Footer />
    </>
  )
}

export default Home
